categories = ["Added", "Changed", "Fixed", "Improved", "Removed", "Updated"]
category_delimiters = ["[", "]"]
colored_output = true
enable_debug = true
excluded_commit_tags = ["Updated"]
enable_footers = false
show_commit_hash = false
show_prefix = false
sort_by = "date"
template_prefix = ""